apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-svc-primary

# mandatory annotation indicating primary service

  annotations:
    harness.io/primary-service: true
  labels:
    app: hello-world
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: hello-world