apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-svc-stage

# mandatory annotation indicating stage service

  annotations:
    harness.io/stage-service: true
  labels:
    app: hello-world
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: hello-world